name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - master  # Or 'main' if that's your default branch
      # Also trigger on pushes to the feature branch for testing
      - feat/minimal-mistakes-theme
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }} # Checkout the branch that triggered the workflow

      - name: Setup Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Or a version compatible with your gems, Minimal Mistakes usually works well with 2.7+ or 3.0+
          bundler-cache: true # Runs bundle install and caches gems

      - name: Build Jekyll site
        run: bundle exec jekyll build --verbose
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Path to the directory to upload
          path: './_site'

  deploy:
    needs: build_and_deploy
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to deploy to GitHub Pages
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
